name: "LIBXSMM"
author: "Hans Pabst"
github: "libxsmm/libxsmm"
copyright: "Copyright (c) 2009-2023, LIBXSMM Contributors."
license: "BSD-3-Clause"
description: "Library for specialized dense and sparse matrix operations, and deep learning primitives."
categories = ["numerical"]
keywords = ["deep-learning", "tensor", "matrix", "vector", "sparse", "intel", "amx", "avx", "sse", "arm", "jit", "simd", "blas", "gemm", "multiplication", "transpose", "convolution"]
homepage = "https://libxsmm.readthedocs.io/"
