site_name: LIBXSMM
site_author: Hans Pabst
copyright: Copyright (c) 2009-2021, LIBXSMM <a href="http://libxsmm.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library targeting Intel Architecture for specialized dense and sparse matrix operations, and deep learning primitives.
repo_url: https://github.com/hfp/libxsmm/
edit_uri: edit/master/documentation
site_url: https://libxsmm.readthedocs.io/
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 3
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

nav:
- Overview: index.md
- Compatibility: libxsmm_compat.md
- Validation: libxsmm_valid.md
- Q&A: libxsmm_qna.md
- LIBXSMM Domains:
  - "MM: Matrix Multiplication": libxsmm_mm.md
  - "DNN: Deep Neural Networks": libxsmm_dl.md
  - "AUX: Service Functions": libxsmm_aux.md
  - "PROF: Performance Profiling": libxsmm_prof.md
  - "TUNE: Customization": libxsmm_tune.md
  - "BE: Backend": libxsmm_be.md
- Example Code:
  - Collection: libxsmm_samples.md
- Machine Learning (ML):
  - PlaidML tensor compiler: https://github.com/plaidml/plaidml
  - Intel Extension for PyTorch: https://github.com/intel/intel-extension-for-pytorch
  - GxM Deeplearning: gxm.md
  - TensorFlow: tensorflow.md
- Scientific (HPC):
  - CP2K: cp2k.md
  - SeisSol: https://seissol.readthedocs.io/en/latest/compilation.html#installing-libxsmm
  - SpECTRE: https://sxs-collaboration.github.io/spectre/installation.html
  - libCEED: https://ceed.exascaleproject.org/ceed-code/
  - Fastor: https://github.com/romeric/Fastor/wiki/9.-Using-the-LIBXSMM-MKL-JIT-backend
  - EDGE: http://usr.dial3343.org/en/master/chapters/install/edge.html#libxsmm
  - PyFR: http://pyfr.org/user_guide.php
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
